import {
  Archive,
  Bot,
  FilePlus2,
  FolderKanban,
  Home,
  Inbox,
  ListTodo,
  Search,
  Sparkles,
  Tags,
  Upload,
  Workflow,
} from "lucide-react";
import type { CommandAction } from "@/components/command/command-types";

export const commandActions: CommandAction[] = [
  {
    id: "nav-home",
    title: "Go to Home",
    description: "Open the AI Activity Hub home dashboard.",
    category: "Navigation",
    shortcut: "G H",
    href: "/",
    icon: Home,
    keywords: ["home", "dashboard", "overview"],
    previewTitle: "Home Dashboard",
    previewBody: "Daily overview of AI activity, inbox pressure, artifacts, timeline, and projects.",
  },
  {
    id: "nav-timeline",
    title: "Go to Timeline",
    description: "Open normalized AI activity events.",
    category: "Navigation",
    shortcut: "G T",
    href: "/timeline",
    icon: Workflow,
    keywords: ["timeline", "events", "activity", "history"],
    previewTitle: "Timeline",
    previewBody: "Chronological stream of chats, imports, artifacts, decisions, and tasks.",
  },
  {
    id: "nav-inbox",
    title: "Go to Inbox",
    description: "Review unprocessed AI work.",
    category: "Navigation",
    shortcut: "G I",
    href: "/inbox",
    icon: Inbox,
    keywords: ["inbox", "triage", "review", "unprocessed"],
    previewTitle: "Inbox",
    previewBody: "Fast triage loop for assigning projects, extracting tasks, saving artifacts, and archiving noise.",
  },
  {
    id: "nav-artifacts",
    title: "Go to Artifacts",
    description: "Open generated output library.",
    category: "Navigation",
    shortcut: "G A",
    href: "/artifacts",
    icon: Archive,
    keywords: ["artifacts", "files", "outputs", "documents", "code"],
    previewTitle: "Artifacts",
    previewBody: "Generated docs, code, diagrams, prototypes, images, and reusable AI outputs.",
  },
  {
    id: "nav-projects",
    title: "Go to Projects",
    description: "Open AI work containers.",
    category: "Navigation",
    shortcut: "G P",
    href: "/projects",
    icon: FolderKanban,
    keywords: ["projects", "work", "outcomes"],
    previewTitle: "Projects",
    previewBody: "Projects group timeline events, inbox items, artifacts, chats, tasks, and decisions.",
  },
  {
    id: "nav-search",
    title: "Go to Search",
    description: "Search across AI work.",
    category: "Navigation",
    shortcut: "G S",
    href: "/search",
    icon: Search,
    keywords: ["search", "find", "ask"],
    previewTitle: "Search",
    previewBody: "Find chats, artifacts, decisions, tasks, projects, and timeline events.",
  },
  {
    id: "action-import",
    title: "Import export ZIP",
    description: "Upload ChatGPT or Claude export archive.",
    category: "Actions",
    shortcut: "I Z",
    icon: Upload,
    keywords: ["import", "zip", "export", "chatgpt", "claude"],
    previewTitle: "Import Export ZIP",
    previewBody: "Start the import flow for historical AI activity and raw export archives.",
  },
  {
    id: "action-upload-artifact",
    title: "Upload artifact",
    description: "Add a document, code file, image, diagram, or prototype.",
    category: "Actions",
    shortcut: "U A",
    icon: FilePlus2,
    keywords: ["upload", "artifact", "file", "document"],
    previewTitle: "Upload Artifact",
    previewBody: "Manual artifact capture for generated files and downloaded AI outputs.",
  },
  {
    id: "action-create-project",
    title: "Create project",
    description: "Create a new work container.",
    category: "Actions",
    shortcut: "C P",
    icon: FolderKanban,
    keywords: ["create", "project", "new"],
    previewTitle: "Create Project",
    previewBody: "Group related AI activity around an outcome, client, product, or topic.",
  },
  {
    id: "action-extract-tasks",
    title: "Extract tasks",
    description: "Create tasks from a chat, inbox item, or artifact.",
    category: "Actions",
    shortcut: "E T",
    icon: ListTodo,
    keywords: ["extract", "tasks", "todo", "action items"],
    previewTitle: "Extract Tasks",
    previewBody: "Convert AI-generated action items into structured project tasks.",
  },
  {
    id: "search-dashboard",
    title: "Find dashboard IA prompt",
    description: "Search for the prompt where dashboard IA was designed.",
    category: "Search",
    icon: Search,
    keywords: ["dashboard", "ia", "prompt", "wireframe", "search"],
    previewTitle: "Search Result",
    previewBody: "Likely matches: AI Activity Hub Planning, Dashboard IA Plan, Inbox Triage Flow.",
  },
  {
    id: "search-ux-research",
    title: "Find UX research outputs",
    description: "Search Claude and ChatGPT outputs related to UX research.",
    category: "Search",
    icon: Tags,
    keywords: ["ux", "research", "outputs", "claude", "chatgpt"],
    previewTitle: "UX Research Outputs",
    previewBody: "Returns artifacts, chats, decisions, and prototypes linked to UX Research.",
  },
  {
    id: "ai-ask-workspace",
    title: "Ask AI about workspace",
    description: "Ask a question across local AI work.",
    category: "AI",
    shortcut: "A W",
    icon: Bot,
    keywords: ["ask", "ai", "workspace", "question"],
    previewTitle: "Ask AI",
    previewBody: "Ask questions like: What did I decide about import-first architecture?",
  },
  {
    id: "ai-summarize-project",
    title: "Summarize current project",
    description: "Generate a short project status summary.",
    category: "AI",
    shortcut: "S P",
    icon: Sparkles,
    keywords: ["summarize", "project", "status", "ai"],
    previewTitle: "Project Summary",
    previewBody: "Summarizes recent activity, open tasks, decisions, and generated artifacts.",
  },
];
